module.exports = {
	entry:["./src/js/test1.js"],
	output:{
		path:__dirname,
		filename:"./src/js/test1-compiled.js"
	},
	module:{
		loaders:[
			{
				test:/\.css$/,
				loader:"style!css"
			},
			{
				test:/\.js$/,
				loader:"babel-loader",
				exclude:/node_modules/,
				query:{
					presets:['es2015','react']
				}
			}
		]
	},
	resolve:['','.js','.css','.less','.json']
}
