module.exports = {
	entry:["./src/js/app-raw.js"],
	output:{
		path:__dirname,
		filename:"./src/js/app.js"
	},
	module:{
		loaders:[
			{
				test:/\.css$/,
				loader:['style','css']
			},
			{
				test:/\.scss$/,
				loader:['style','css','sass']
			},
			{
				test:/\.js$/,
				loader:["babel"],
				exclude:/node_modules/,
				query:{
					presets:['es2015','react']
				}
			}
		]
	},
	resolve:['','.js','.css','.scss','.json']
}
